### ISSUE TITLE
Setting replication mode

### ISSUE THREAD

**Issue by phoenix-bjoern** [piraeusdatastore/linstor-csi#100]
According to https://www.linbit.com/drbd-user-guide/drbd-guide-9_0-en/#s-replication-protocols DRBD supports 3 replication modes.
Is it possible to define a storage class for each of these modes/protocols in order to decide per workload what the best choice for security and performance is?

**Comment by WanzenBug** [comment]
Yes, it's possible. Use the `DrbdOptions/Net/protocol` parameter in your storage class. For example:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-drbd-b
provisioner: linstor.csi.linbit.com
parameters:
  layerlist: storage
  autoPlace: "2"
  storagePool: "some-pool"
  resourceGroup: "drbd-b"
  DrbdOptions/Net/protocol: B
```
