### ISSUE TITLE
With "layerlist: storage", "placementPolicy: FollowTopology" creates a drbd device instead of an LV

### ISSUE THREAD

**Issue by dkhachyan** [piraeusdatastore/linstor-csi#102]
Hi!
I'm using the latest piraeus-operator. With layerlist: storage, placementPolicy: FollowTopology creates a drbd device instead of an LV.

sc.yaml

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-hdd-lvm
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  layerlist: storage
  placementCount: "1"
  placementPolicy: FollowTopology
  allowRemoteVolumeAccess: "false"
  disklessOnRemaining: "false"
  csi.storage.k8s.io/fstype: xfs
  mountOpts: noatime,discard
  storagePool: hdd
```
  
 oc -n piraeus-demo get pvc

```
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
linstor-lvm   Bound    pvc-15523a8a-e0d2-48c3-9fa4-e79725def3cd   23Gi       RWO            linstor-hdd-lvm   9s
```

kubectl -n piraeus-demo describe pv pvc-15523a8a-e0d2-48c3-9fa4-e79725def3cd

```
Name:              pvc-15523a8a-e0d2-48c3-9fa4-e79725def3cd
Labels:            <none>
Annotations:       pv.kubernetes.io/provisioned-by: linstor.csi.linbit.com
Finalizers:        [kubernetes.io/pv-protection external-attacher/linstor-csi-linbit-com]
StorageClass:      linstor-hdd-lvm
Status:            Bound
Claim:             piraeus-demo/linstor-lvm
Reclaim Policy:    Delete
Access Modes:      RWO
VolumeMode:        Filesystem
Capacity:          23Gi
Node Affinity:
  Required Terms:
    Term 0:        linbit.com/hostname in [intel-1]
Message:
Source:
    Type:              CSI (a Container Storage Interface (CSI) volume source)
    Driver:            linstor.csi.linbit.com
    FSType:            xfs
    VolumeHandle:      pvc-15523a8a-e0d2-48c3-9fa4-e79725def3cd
    ReadOnly:          false
    VolumeAttributes:      storage.kubernetes.io/csiProvisionerIdentity=1608004506593-8081-linstor.csi.linbit.com
Events:                <none>
```

┊ intel-1 ┊ pvc-15523a8a-e0d2-48c3-9fa4-e79725def3cd ┊ raid10      ┊     0 ┊    1013 ┊ /dev/drbd1013 ┊  23.01 GiB ┊ InUse  ┊ UpToDate ┊
