### ISSUE TITLE
Configuration files related to k8s deployment need to be updated

### ISSUE THREAD

**Issue by cumirror** [piraeusdatastore/linstor-csi#104]
some configuration files, such as linstor-csi-[1.17|1.19|dev].yaml in examples/k8s/deploy folder, has linstor-csi-snapshotter-role define but lack of linstor-csi-snapshotter-binding:
```
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linstor-csi-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: linstor-csi-controller-sa
    # You must change this to the current context
    namespace: default
roleRef:
  kind: ClusterRole
  name: linstor-csi-snapshotter-role
  apiGroup: rbac.authorization.k8s.io

```
