### ISSUE TITLE
Ephimeral volumes support

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/linstor-csi#156]
Hey I just trying to use ephimeral volumes feature

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - args:
    - -c
    - |
      echo 123 > /data/some_file
      cat /data/some_file
    command:
    - /bin/sh
    image: alpine
    name: test
    volumeMounts:
    - mountPath: /data
      name: data
  restartPolicy: Never
  volumes:
  - csi:
      driver: linstor.csi.linbit.com
      volumeAttributes:
        linstor.csi.linbit.com/placementCount: "1"
        linstor.csi.linbit.com/storagePool: data
    name: data
```

But I see the following error message:

```
MountVolume.NewMounter initialization failed for volume "data" : volume mode "Ephemeral" not supported by driver linstor.csi.linbit.com (only supports ["Persistent"])
```

**Comment by kvaps** [comment]
However this example works perfectly:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - args:
    - -c
    - |
      echo 123 > /data/some_file
      cat /data/some_file
    command:
    - /bin/sh
    image: alpine
    name: test
    volumeMounts:
    - mountPath: /data
      name: data
  restartPolicy: Never
  volumes:
  - name: data
    ephemeral:
      volumeClaimTemplate:
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "linstor-data-r1"
          resources:
            requests:
              storage: 1Gi
```
