### ISSUE TITLE
kubevirt: allow-two-primaries must be set to perform live-migration

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/linstor-csi#159]
To reproduce:

Install KubeVirt and enable featureGates: `LiveMigration` and `HotplugVolumes`

```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: kubevirt
  namespace: kubevirt
spec:
  configuration:
    developerConfiguration:
      featureGates:
      - LiveMigration
      - HotplugVolumes
  imagePullPolicy: IfNotPresent
```

Create VM:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: testvm1
  namespace: default
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - containerDisk:
          image: kubevirt/fedora-cloud-container-disk-demo:latest
        name: containerdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
```

Create volume:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: linstor-data-r2
  resources:
    requests:
      storage: 100Gi
```

attach volume to the vm:
```
virtctl addvolume testvm --volume-name my-pvc
```

run live-migration:
```
virtctl migrate testvm1
```

You'll see that hotplug-volume pod will be failed to run on second node:

```
hp-volume-29d84               1/1     Running             0          2m4s
hp-volume-6lvvm               0/1     ContainerCreating   0          77s
```

Due to:
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               86s               default-scheduler        Successfully assigned default/hp-volume-6lvvm to hf-kubevirt-01
  Normal   SuccessfulAttachVolume  85s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-2a81bf2c-65dd-4782-b011-3c37af658575"
  Warning  FailedMapVolume         5s (x8 over 70s)  kubelet                  MapVolume.MapPodDevice failed for volume "pvc-2a81bf2c-65dd-4782-b011-3c37af658575" : rpc error: code = Internal desc = NodePublishVolume failed for pvc-2a81bf2c-65dd-4782-b011-3c37af658575: failed to set source device readwrite: exit status 1
```

If you'd go on csi-node pod and run [this command](https://github.com/piraeusdatastore/linstor-csi/blob/2a6035bfe262254fc254293a9e71ac40efeb326e/pkg/client/linstor.go#L1704-L1707), you'll see the error:
```
# blockdev --setrw /dev/drbd1000
blockdev: cannot open /dev/drbd1000: Wrong medium type
```

But after adding this option:
```
linstor rd sp pvc-2a81bf2c-65dd-4782-b011-3c37af658575 DrbdOptions/Net/allow-two-primaries yes
```

everything is starting working as it should.

Thus I think that we need to set `allow-two-primaries` automatically for any volume with `accessMode: ReadWriteMany` and  `type: Block`.
We have two options how we can do that:
- Set it on volume creation
- Set it on volume attachment

Which option do you prefer more?

**Comment by rck** [comment]
This is like 100 years ago, but back then I just set it on the storage class. This does not work any more? Not for you? https://github.com/piraeusdatastore/linstor-csi/tree/master/examples/kubevirt

**Comment by WanzenBug** [comment]
First thing: I'm surprised it even lets you have a `ReadWriteMany` resource at all...

Secondly: I'd prefer it if the user had to explicitly opt-in (maybe through a new `enable-live-migration` parameter on the storage class?). Then, on volume attach, if CSI can reasonably think it is in a live-migration situation: enable `allow-two-primaries`. And on detach on the old node: set it back to false.

**Comment by kvaps** [comment]
@rck sorry, I didn't see that doc, but any way this is not working in my case:

```yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-data-r2
parameters:
  linstor.csi.linbit.com/placementCount: "2"
  linstor.csi.linbit.com/storagePool: data
  DrbdOptions/Net/allow-two-primaries: "yes"
provisioner: linstor.csi.linbit.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```


```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: linstor-data-r2
  resources:
    requests:
      storage: 100Gi
```

```console
# linstor rd lp pvc-e9e280d1-b648-40d5-a4bf-35bd976fa24a
╭─────────────────────────────────────────────────────────╮
┊ Key                               ┊ Value               ┊
╞═════════════════════════════════════════════════════════╡
┊ Aux/csi-provisioning-completed-by ┊ linstor-csi/v0.18.0 ┊
┊ DrbdOptions/Resource/on-no-quorum ┊ io-error            ┊
┊ DrbdOptions/Resource/quorum       ┊ majority            ┊
┊ DrbdOptions/auto-verify-alg       ┊ crct10dif-pclmul    ┊
┊ DrbdPrimarySetOn                  ┊ HF-KUBEVIRT-01      ┊
╰─────────────────────────────────────────────────────────╯
```
