### ISSUE TITLE
LINSTOR CSI may fail to restore from snapshot with advanced scheduling constraints

### ISSUE THREAD

**Issue by WanzenBug** [piraeusdatastore/linstor-csi#160]
Basically using:

```yaml
parameters:
   replicasOnDifferent: topology.kubernetes.io/zone
   replicasOnSame: topology.kubernetes.io/region
```
may lead to snapshots that can't be restored, because LINSTOR doesn't want to autoplace. I thought I had fixed these issues in #148 but apparently not...
