### ISSUE TITLE
Failed to set fsGroup with RWX pvc

### ISSUE THREAD

**Issue by bc185174** [piraeusdatastore/linstor-csi#178]
Hi, I have been trying to provision a RWX pvc, where both devices can temporarily be primary (this is based on issue https://github.com/piraeusdatastore/linstor-csi/issues/159). 

The issue I am seeing is the fsGroup does not get set for the RWX volume but it does for RWO volume:

```
kubectl exec -ti fsgroup-test-79d595bb7c-2v92x -- ls -la /
drwxrwsr-x    3 root     107           4096 Nov  7 14:10 data-rwo
drwxr-xr-x    3 root     root          4096 Nov  7 14:10 data-rwx
```

## Reproducing the issue

1. Install Linstor configured with lvm thick pool.

2. Create StorageClass:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: linstor-cluster-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "2"
  storagePool: "lvm-thick"
  DrbdOptions/Net/allow-two-primaries: "yes"
allowVolumeExpansion: true
```

3. Create Test pod:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsgroup-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsgroup-test
  template:
    metadata:
      labels:
        app: fsgroup-test
    spec:
      securityContext:
        fsGroup: 107
        runAsUser: 107
      containers:
        - name: debug
          image: alpine:3.11
          command: ["/bin/sh"]
          stdin: true
          tty: true
          volumeMounts:
          - mountPath: /data-rwx
            name: linstor-fsgroup-test-rwx
          - mountPath: /data-rwo
            name: linstor-fsgroup-test-rwo
      volumes:
      - name: linstor-fsgroup-test-rwx
        persistentVolumeClaim:
          claimName: linstor-fsgroup-test-rwx
          readOnly: false
      - name: linstor-fsgroup-test-rwo
        persistentVolumeClaim:
          claimName: linstor-fsgroup-test-rwo
          readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linstor-fsgroup-test-rwx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor-cluster-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linstor-fsgroup-test-rwo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor-cluster-storage
```

**Note**: post provisioning, I set the user to root and I could change the fs group manually.
