### ISSUE TITLE
Snapshot creation failed

### ISSUE THREAD

**Issue by am6737** [piraeusdatastore/linstor-csi#203]
hi
I'm on the basis https://piraeus.io/site/docs/optional-components#using-snapshots
Failed to create snapshot successfully

linstor-csi-controller version
```
csi-provisioner      quay.io/k8scsi/csi-provisioner:v2.0.2
csi-attacher         quay.io/k8scsi/csi-attacher:v3.0.0
csi-resizer          quay.io/k8scsi/csi-resizer:v1.0.0
csi-snapshotter      quay.io/k8scsi/csi-snapshotter:v3.0.0
linstor-csi-plugin   quay.io/piraeusdatastore/piraeus-csi:v1.2.0(v1.0.0 also tried)
````
linstor version v1.23.0

snapshot cd version v6.2.0

kubectl describe volumesnapshots.snapshot.storage.k8s.io my-first-linstor-snapshot
```yaml
Name:         my-first-linstor-snapshot
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  snapshot.storage.k8s.io/v1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:  2023-06-22T05:45:29Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
  Generation:  1
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-06-22T05:45:29Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection":
          v:"snapshot.storage.kubernetes.io/volumesnapshot-bound-protection":
    Manager:      snapshot-controller
    Operation:    Update
    Time:         2023-06-22T05:45:29Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:readyToUse:
    Manager:         snapshot-controller
    Operation:       Update
    Subresource:     status
    Time:            2023-06-22T05:45:29Z
  Resource Version:  5693061
  UID:               e5f9cc0b-667f-431e-86c0-f75e0160a2e4
Spec:
  Source:
    Persistent Volume Claim Name:  lms-test-pvc
  Volume Snapshot Class Name:      my-first-linstor-snapshot-class
Status:
  Bound Volume Snapshot Content Name:  snapcontent-e5f9cc0b-667f-431e-86c0-f75e0160a2e4
  Ready To Use:                        false
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  7m9s  snapshot-controller  Waiting for a snapshot default/my-first-linstor-snapshot to be created by the CSI driver.
```

linstor-csi-controller csi-snapshotter log
```
E0622 05:55:04.964637       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotContent: failed to list *v1beta1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)
E0622 05:55:15.071563       1 reflector.go:127] github.com/kubernetes-csi/external-snapshotter/client/v3/informers/externalversions/factory.go:117: Failed to watch *v1beta1.VolumeSnapshotClass: failed to list *v1beta1.VolumeSnapshotClass: the server could not find the requested resource (get volumesnapshotclasses.snapshot.storage.k8s.io)
```
