### ISSUE TITLE
Pod stuck in Terminating status and won't unbind pvc

### ISSUE THREAD

**Issue by volodaiy** [piraeusdatastore/linstor-csi#204]
Hi all!

deployed linstor in HA mode on k3s (3 master (controller ) nodes), i.e. controller is installed on the master node.
what it looks like:
k3s
```
NAME           STATUS   ROLES                       AGE    VERSION
k3s-master01   Ready    control-plane,etcd,master   4d1h   v1.26.1+k3s1
k3s-master02   Ready    control-plane,etcd,master   4d     v1.26.1+k3s1
k3s-master03   Ready    control-plane,etcd,master   4d1h   v1.26.1+k3s1
``` 
linstor
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node         ┊ Diskless ┊ LVM ┊ LVMThin ┊ ZFS/Thin ┊ File/Thin ┊ SPDK ┊ EXOS ┊ Remote SPDK ┊ Storage Spaces ┊ Storage Spaces/Thin ┊
╞═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ k3s-master01 ┊ +        ┊ +   ┊ +       ┊ -        ┊ +         ┊ -    ┊ -    ┊ +           ┊ -              ┊ -                   ┊
┊ k3s-master02 ┊ +        ┊ +   ┊ +       ┊ -        ┊ +         ┊ -    ┊ -    ┊ +           ┊ -              ┊ -                   ┊
┊ k3s-master03 ┊ +        ┊ +   ┊ +       ┊ -        ┊ +         ┊ -    ┊ -    ┊ +           ┊ -              ┊ -                   ┊
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────────────────────────────────────────────╮
┊ Node         ┊ DRBD ┊ LUKS ┊ NVMe ┊ Cache ┊ BCache ┊ WriteCache ┊ OpenFlex ┊ Storage ┊
╞══════════════════════════════════════════════════════════════════════════════════════╡
┊ k3s-master01 ┊ +    ┊ +    ┊ -    ┊ +     ┊ +      ┊ +          ┊ -        ┊ +       ┊
┊ k3s-master02 ┊ +    ┊ +    ┊ -    ┊ +     ┊ +      ┊ +          ┊ -        ┊ +       ┊
┊ k3s-master03 ┊ +    ┊ +    ┊ -    ┊ +     ┊ +      ┊ +          ┊ -        ┊ +       ┊
╰──────────────────────────────────────────────────────────────────────────────────────╯
```
```
╭──────────────────────────────────────────────────────────────────────────────────────╮
┊ ResourceName ┊ Node         ┊ Port ┊ Usage  ┊ Conns ┊    State ┊ CreatedOn           ┊
╞══════════════════════════════════════════════════════════════════════════════════════╡
┊ linstor_db   ┊ k3s-master01 ┊ 7000 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2023-06-21 15:58:38 ┊
┊ linstor_db   ┊ k3s-master02 ┊ 7000 ┊ Unused ┊ Ok    ┊ UpToDate ┊ 2023-06-21 15:58:38 ┊
┊ linstor_db   ┊ k3s-master03 ┊ 7000 ┊ InUse  ┊ Ok    ┊ UpToDate ┊ 2023-06-21 15:58:39 ┊
╰──────────────────────────────────────────────────────────────────────────────────────╯
```
- installed csi 1.19 https://raw.githubusercontent.com/piraeusdatastore/linstor-csi/master/examples/k8s/deploy/linstor-csi-1.19.yaml
- created storageclass according to instructions from official documentation.
- I create a test deployment + pvc, everything works well.
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-vol-claim-0
  namespace: default
spec:
  storageClassName: linstor-r3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-pod-0
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: demo-pod-0
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 1000s; done"]
        volumeMounts:
          - mountPath: "/data"
            name: demo-vol
      volumes:
        - name: demo-vol
          persistentVolumeClaim:
            claimName: demo-vol-claim-0
``` 
- but when I try to check HA and disable one node, it freezes in Terminating.
```
NAME                          READY   STATUS              RESTARTS   AGE
demo-pod-0-5b87665bc8-7xnpz   1/1     Terminating         0          8m8s
demo-pod-0-5b87665bc8-f9l6k   0/1     ContainerCreating   0          23s
```
- the old pod cannot unmount pvc, and the new pod cannot mount because of this:
Warning FailedAttachVolume 118s attachdetach-controller Multi-Attach error for volume "pvc-3af7a2db-aff2-4983-b69d-2e191695c328" Volume is already used by pod(s) demo-pod-0-5b87665bc8-7xnpz

**Whether it is possible to solve it somehow?**
