### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by kvaps** [piraeusdatastore/linstor-csi#65]
Hi, is there any option to use certificate based authentication with linstor-csi plugin?

**Comment by NeonSludge** [comment]
Hi.

My pull request to support TLS mutual auth has been merged in February: eb0b344. 
So now you can pass three environment variables to linstor-csi-plugin to make it use certificate based auth, provided that the controller itself is set up to verify client certificates:

`LS_USER_CERTIFICATE`: a client certificate that is trusted by the LINSTOR controller.
`LS_USER_KEY`: corresponding private key.
`LS_ROOT_CA`: certificate authority certificate (or chain) that the client will use to verify server certificates.

We've tested this in our cluster (k8s v1.17.4) and it works.

**Comment by kvaps** [comment]
Awesome! I didn't know about that so used stunnel, now I have to update my manifests :)

**Comment by kvaps** [comment]
@NeonSludge do you have any idea why this change is not working for me?

```yaml
env:
  - name: LS_USER_CERTIFICATE
    value: /tls/tls.crt
  - name: LS_USER_KEY
    value: /tls/tls.key
  - name: LS_ROOT_CA
    value: /tls/ca.crt
```

When I specify these variables my linstor-csi-plugin can't start:

```
time="2020-04-09T11:29:15Z" level=fatal msg="tls: failed to find any PEM data in certificate input"
```

```bash
# ls -lah /tls/
total 4.0K
drwxrwxrwt 3 root root  140 Apr  9 11:35 .
drwxr-xr-x 1 root root 4.0K Apr  9 11:35 ..
drwxr-xr-x 2 root root  100 Apr  9 11:35 ..2020_04_09_11_35_24.179124466
lrwxrwxrwx 1 root root   31 Apr  9 11:35 ..data -> ..2020_04_09_11_35_24.179124466
lrwxrwxrwx 1 root root   13 Apr  9 11:35 ca.crt -> ..data/ca.crt
lrwxrwxrwx 1 root root   14 Apr  9 11:35 tls.crt -> ..data/tls.crt
lrwxrwxrwx 1 root root   14 Apr  9 11:35 tls.key -> ..data/tls.key
```

curl is working:

```bash
# curl --cacert /tls/ca.crt --cert /tls/tls.crt --key /tls/tls.key https://linstor-controller:3371/v1/controller/properties
{"DrbdOptions/Net/after-sb-0pri":"disconnect","DrbdOptions/Net/after-sb-1pri":"disconnect","DrbdOptions/Net/after-sb-2pri":"disconnect","DrbdOptions/Net/csums-alg":"crc32","DrbdOptions/Net/max-buffers":"36864","DrbdOptions/Net/protocol":"C","DrbdOptions/Net/rcvbuf-size":"2097152","DrbdOptions/Net/sndbuf-size":"1048576","DrbdOptions/Net/verify-alg":"crc32","DrbdOptions/PeerDevice/c-fill-target":"10240","DrbdOptions/PeerDevice/c-max-rate":"737280","DrbdOptions/PeerDevice/c-min-rate":"20480","DrbdOptions/PeerDevice/c-plan-ahead":"10","DrbdOptions/auto-add-quorum-tiebreaker":"true","DrbdOptions/auto-quorum":"io-error","TcpPortAutoRange":"7000-9999","defaultDebugSslConnector":"DebugSslConnector","defaultPlainConSvc":"PlainConnector","defaultSslConSvc":"SslConnector","netcom/DebugSslConnector/bindaddress":"::0","netcom/DebugSslConnector/enabled":"true","netcom/DebugSslConnector/keyPasswd":"linstor","netcom/DebugSslConnector/keyStore":"ssl/keystore.jks","netcom/DebugSslConnector/keyStorePasswd":"linstor","netcom/DebugSslConnector/port":"3373","netcom/DebugSslConnector/sslProtocol":"TLSv1.2","netcom/DebugSslConnector/trustStore":"ssl/certificates.jks","netcom/DebugSslConnector/trustStorePasswd":"linstor","netcom/DebugSslConnector/type":"ssl","netcom/PlainConnector/bindaddress":"127.0.0.1","netcom/PlainConnector/enabled":"true","netcom/PlainConnector/port":"3376","netcom/PlainConnector/type":"plain","netcom/SslConnector/bindaddress":"::0","netcom/SslConnector/enabled":"true","netcom/SslConnector/keyPasswd":"linstor","netcom/SslConnector/keyStore":"ssl/keystore.jks","netcom/SslConnector/keyStorePasswd":"linstor","netcom/SslConnector/port":"3377","netcom/SslConnector/sslProtocol":"TLSv1.2","netcom/SslConnector/trustStore":"ssl/certificates.jks","netcom/SslConnector/trustStorePasswd":"linstor","netcom/SslConnector/type":"ssl"}
```

controller certs:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: linstor-controller-tls
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQVAvekY3OWE1eXdEcnFxR3JNcjQ3bUF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2JHbHVjM1J2Y2kxallUQWVGdzB5TURBME1Ea3hNRFF5TURkYUZ3MHpNREEwTURjeApNRFF5TURkYU1CVXhFekFSQmdOVkJBTVRDbXhwYm5OMGIzSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUNXMFBXdS96UllKRlVEMWV1bVFwcXBacVBlYXBXK2FsaU1KMFpxQ0twTWpRd3AKM0l0STcvSGRKd1VVL0ZJYk1yZUZmS3o4VFpJTEtvN0F0V0RqRENoYm50M1FLZUR6M3Y0a0VRUVh5UjJYQitHSwpoU1AwT3VJVWduNUtBMEVlcGlIREZFMkVldlB4bHZ2MEN5NEpjZXplVXh5ZEQzMUVoSTg4NFdtNEhJVkpJaXVWCmNHNjZ3TTM0Y1RlYmZuZ2xXdjRINCtTd1pUZU90eHhHT3J0NHg5VnNPc1RlcWQvVXpSSEZONUpCTjZHTFoyZ3IKQlBIUk55MTY5MnRJM2tONkVnRm5XUWs4Uys2VTZPcnBLSmROcmFzem9oc1FjQmx6WEJGWEtpMEh4RndPR2FUVQplOE9oSkJxa1huSEN0QnVlNUJRWDE5UEttYXRxVktDMDhRbkU5Mll6QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCCi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaDk4N25ReENhVExQWHUwT2RNMk5rQWgxY1J6dwpaWVpTcGlOUlhVN0M4TVFZdkpwSks5S0ZOdDNkNnpCcEdPcUN1Z3F1M3hGVHU5MmZZTCtYMjlOdzIzUmJ3cGFxCnBqVm5CN2QwZXUwbXNyaDFwd2E1R3lvWVhwSXdkd0h3UUhCRHAwTWZRcGtTczBJc3E4cW1EOGhLdXNlMFFxKzIKUzliMmdiUkM3eCsvY3p2cWEyZkoxenBNb21SUksrcGNnc09sTnk2K0xwbjVtdFdoeUpLYUZSWkw1Mkd3YWZpdwpUR0Y0ZzZtOWdXT3lIQTlaUVRLTk9Dc3R1TWN0SS8wU1d5ZGIvNzRGRHFMZ1c2WXNObElDQ3R5V2U0U2pPTTNsClJwcDQ4b3owdStiZ2JONVlHS1dhSjZHRGJPLzNqOFdrZTJVRDBVdU0wR3U2b3g5NEJ5b1hrTXJIeUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURhakNDQWxLZ0F3SUJBZ0lSQUxRT0VHWG52ZXUzcXVFUHlEZ25pVk13RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2JHbHVjM1J2Y2kxallUQWVGdzB5TURBME1Ea3hNRFF5TURkYUZ3MHpNREEwTURjeApNRFF5TURkYU1CMHhHekFaQmdOVkJBTVRFbXhwYm5OMGIzSXRZMjl1ZEhKdmJHeGxjakNDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT1F1OHp3Y3Bra3M4aWtaZHFCSjh6UTRUOFVIVnkrTUNGZVkKbUloNllhZ3RVNThNMTlpNkttc2t6aEhSbnNFaTliTXdWdG1YdDRMTlluaGdxUkhlSnIzajFoUzBCWk5NL2dreApVT21qV3pjb0Y4aUoyeUNHdGF6d3B0RjlQQzFEL3JqYzBHN3dtRkd3YWQ4eTJoeDBXRzJzZXFYeFhSVGZ6TW5lCkRVUnJUSUR2TlkrMnBkMlYrZE9CSndJVURTZnF6eEc1emNab2Z0ZFlZUE5KRDlMSnNsVGhBd25rbjVhZEJ4TVAKTEtnN1JpN3g3OUVyL2U2TGh2U28rWFFoRUFyalAxaFd0SHNySFlpanN0aVdYcFpaSmFaT1RQNXRnOHV4TDh6Zgo3QVFBQitmcW5xaXBLYWpObHBJUWNkaDF1aU5IR1ZZRmhpMm4wNVVXSDMwdXAzWFF3Tk1DQXdFQUFhT0JyRENCCnFUQU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUMKTUF3R0ExVWRFd0VCL3dRQ01BQXdhZ1lEVlIwUkJHTXdZWUlTYkdsdWMzUnZjaTFqYjI1MGNtOXNiR1Z5Z2hwcwphVzV6ZEc5eUxXTnZiblJ5YjJ4c1pYSXViR2x1YzNSdmNvSWViR2x1YzNSdmNpMWpiMjUwY205c2JHVnlMbXhwCmJuTjBiM0l1YzNaamdnbHNiMk5oYkdodmMzU0hCSDhBQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFBTysKT2ZvYXN4ajJ0Rmh6MTNUUnJFSmZoRzhDQmFDeGk2RWo5dGRLZlpJRDl4NEFNNnc0ZUNYcVJ5QUpVa2JKRFU5TgpqbnBNRDhDdkp6eHkxandLWkdsTnlRaXZRQ0pwNHNyMHhSS2x0ci9WOHVFV3hkU0ZzTXlReTZBYWpTYis2UWdhCmZNOUx2MVNyd2JVT003eFZlSVFDdmlaSm1qaTlRbXR2OVI0emlqSml3bk43dTlZbFltbHhPN3FDQ0RpM2JlQk8KYzBLMzBhekFQUFdkVWlxT0JiN2pZMmRWSHFoQkZiZWRvOExDMTBnZVR0bTZRUU96NGlyMnV3YkxOVUExaVBZbwpoU0JMWFFBeUs4VzM5Y0JSOHdxWjQzK01wM3JYQ3R2Tm9oQ0pLWmZvOVh5SmpSaXRvREgvSllrQnM4c3poS1dTCjcyZXZTWEpFZlZER0pqSGJIcW89Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBNUM3elBCeW1TU3p5S1JsMm9FbnpORGhQeFFkWEw0d0lWNWlZaUhwaHFDMVRud3pYCjJMb3FheVRPRWRHZXdTTDFzekJXMlplM2dzMWllR0NwRWQ0bXZlUFdGTFFGazB6K0NURlE2YU5iTnlnWHlJbmIKSUlhMXJQQ20wWDA4TFVQK3VOelFidkNZVWJCcDN6TGFISFJZYmF4NnBmRmRGTi9NeWQ0TlJHdE1nTzgxajdhbAozWlg1MDRFbkFoUU5KK3JQRWJuTnhtaCsxMWhnODBrUDBzbXlWT0VEQ2VTZmxwMEhFdzhzcUR0R0x2SHYwU3Y5CjdvdUc5S2o1ZENFUUN1TS9XRmEwZXlzZGlLT3kySlplbGxrbHBrNU0vbTJEeTdFdnpOL3NCQUFINStxZXFLa3AKcU0yV2toQngySFc2STBjWlZnV0dMYWZUbFJZZmZTNm5kZERBMHdJREFRQUJBb0lCQUhlWU4vb0FsaEx5VUxYRAoxODNwRkdRQlE2WGoxQWxpbnBpeXJQZVRGUTRkTzUrNERvVlVCWm1FZjlFTkNlVDJXc3FoQWxRblZaSmo3VUZrCmdCaVNVOEhnNFRxV28vbHhPQkEvWGNZbXpVOGFYMlRIQkNlSEV6OWlIanpjSTZjaDVTYWs3VVhJS2oxZWRnNzYKeXlCd3hrd3RRMWNvS3Y0ZTBtblhUU0xZRGcvZzBxakJMcktENjdJMWxKelJvMVdFMmw0RDVabDcxcUs4NzB6NgpORzhSYVlkcEVtaGhQWGpuK0E2SXo1b1haZzBKQUF0a1J2ZXZ2cXhCVmxqbEJGSWwrVXJMbmwxaW5Vak95Z0RtCjFIRWU4cjRxRlg4T2oyUWJKMFYvTUdvQzNucndaRFAxdll5UG1hRnRTNGNTeFhUVUJIM29FQjFxdnNYRW85aXcKMzA1eUc4a0NnWUVBNkdwaTJBeXB0MU5YOFBGYUtmRU5kdnNEVWp0Zkt2a3p1RTBzQTk3Q1M2Q1E3YktyNTJyUgordDFUWE1majBYWnNRcVV2YXlyUVlsN0dLKzJ2c3gzVm05RG5PbkFpbDRub1dzU2Y5aW82SjVsOEFQNlJwakVmCnp2MTBVeVc3Ykt4ZnNxWE9SWWxZRzJINVBtTzZBRUp0TW4wZVdlWXNHZ3Z5NkxBaEVTMi9iTTBDZ1lFQSsxYWYKUVB6NDhXdGhWVHI5WFhTdGUzdkxiNExqRzdMRlBTZjkxcHB3U2Z0dWRKQXIvNWRacXJieUd2NjBiQ2QzUHowTgpKMEd4M21xVm41c20yT0d0alhaemNNT2ljMmxyYjNQZUtUalhsa295amNGalhSaUNzMWlyYnBZZFFGaUZRYk84ClFYK0dtMGVtVzFsQ2VJTUh5WFFjK2JGWWNQWi9uRlJhOUttczVCOENnWUFIT3lBZUpxNjFGSE84L0ZWWXpyWWoKaUlXKzdqZjB4MUlUbnRzS3Q4aUZ2OVlpZnhlWUdKdTEyV0w1bFFLQ2h0T3hjeUE1amxoelp3MTFXbXpIL3RxaApnV3RnUnhMY2NoNzNpL3lLRlNCQUVTZHBoSUlWa0p1enZmRDdrVVgyaUpwbG5ZRUFhdGlCNlpkdW1IMjErbHNaCllna3F0TjJVWmVERjJvejgwdGFNMVFLQmdHOGU4aFA2aEZuQVh1MGV3b3dDSFAwK1UwZys5d2YwOXUwOTlDVmcKYklyWkJoRzArQzd0akhCRXFDKzFNckdxbFRjNVY4cG1haXhxdFRJMmwydEdBOFJLZldsNnBTVWZrNmRYOC80SApxcEZBeHE4VHRFbWhuNCtKZ1duSUpyQ2ZNbk5FOHRPR2ZVM0QxTklJV2JJTVJISVZ5d1crR2RyL3NKVytXZVJYCjdCK0RBb0dBREhRbFMwWUhwWjlUQ3E2YTRmZngvNTB3OXI0RDIyMjMxb0lxeUNpazRGQUhza1BBVXpHUUVWQUIKSS9WVStaQWdvb0FreHBCVUdRTGJqb3lSYVJJUENVOTEyZVprRThmcUVPYXVGY0pXa3o5WWxwN1VQdHEwWWRNWgpmN3crRDR3YjUzYW1BSzJ1REtxWFVrR0dsMlAvNk5nV1JBcktFNjFjVENITllSVi9WNkU9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

client certs:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: linstor-client-tls
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5ekNDQWQrZ0F3SUJBZ0lSQVAvekY3OWE1eXdEcnFxR3JNcjQ3bUF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2JHbHVjM1J2Y2kxallUQWVGdzB5TURBME1Ea3hNRFF5TURkYUZ3MHpNREEwTURjeApNRFF5TURkYU1CVXhFekFSQmdOVkJBTVRDbXhwYm5OMGIzSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJEd0F3Z2dFS0FvSUJBUUNXMFBXdS96UllKRlVEMWV1bVFwcXBacVBlYXBXK2FsaU1KMFpxQ0twTWpRd3AKM0l0STcvSGRKd1VVL0ZJYk1yZUZmS3o4VFpJTEtvN0F0V0RqRENoYm50M1FLZUR6M3Y0a0VRUVh5UjJYQitHSwpoU1AwT3VJVWduNUtBMEVlcGlIREZFMkVldlB4bHZ2MEN5NEpjZXplVXh5ZEQzMUVoSTg4NFdtNEhJVkpJaXVWCmNHNjZ3TTM0Y1RlYmZuZ2xXdjRINCtTd1pUZU90eHhHT3J0NHg5VnNPc1RlcWQvVXpSSEZONUpCTjZHTFoyZ3IKQlBIUk55MTY5MnRJM2tONkVnRm5XUWs4Uys2VTZPcnBLSmROcmFzem9oc1FjQmx6WEJGWEtpMEh4RndPR2FUVQplOE9oSkJxa1huSEN0QnVlNUJRWDE5UEttYXRxVktDMDhRbkU5Mll6QWdNQkFBR2pRakJBTUE0R0ExVWREd0VCCi93UUVBd0lDcERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBaDk4N25ReENhVExQWHUwT2RNMk5rQWgxY1J6dwpaWVpTcGlOUlhVN0M4TVFZdkpwSks5S0ZOdDNkNnpCcEdPcUN1Z3F1M3hGVHU5MmZZTCtYMjlOdzIzUmJ3cGFxCnBqVm5CN2QwZXUwbXNyaDFwd2E1R3lvWVhwSXdkd0h3UUhCRHAwTWZRcGtTczBJc3E4cW1EOGhLdXNlMFFxKzIKUzliMmdiUkM3eCsvY3p2cWEyZkoxenBNb21SUksrcGNnc09sTnk2K0xwbjVtdFdoeUpLYUZSWkw1Mkd3YWZpdwpUR0Y0ZzZtOWdXT3lIQTlaUVRLTk9Dc3R1TWN0SS8wU1d5ZGIvNzRGRHFMZ1c2WXNObElDQ3R5V2U0U2pPTTNsClJwcDQ4b3owdStiZ2JONVlHS1dhSjZHRGJPLzNqOFdrZTJVRDBVdU0wR3U2b3g5NEJ5b1hrTXJIeUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lRVDcxVVVsYitBYmdPRjA5SnhwN2c0ekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwc2FXNXpkRzl5TFdOaE1CNFhEVEl3TURRd09URXdOREl3T0ZvWERUTXdNRFF3TnpFdwpOREl3T0Zvd0hURWJNQmtHQTFVRUF4TVNiR2x1YzNSdmNpMWpiMjUwY205c2JHVnlNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzNWFZWXBSeXZKbG1RTEd5VllFYmxYelB1eWR2YngwblgrNFUKdStQNTJzYmNBZHVFVHVwRHI0aWNlZjFUTGYvem56c2tNdkRnN2NEeHluWWk4YzJzU3ZFbXBMK2xuN0NrZWpCTApiOThWdTJOZlVlT3FpTGR2N0MzYXh2dVJpclNnT3VpZ3l4a0Vib3VWYmRadlJSWC93Vk5vaWVQdHNObzA3VkltCmpITWNEQnNmWXVJNngvNERVMms1QWRabUJBZC9taVdxV0JDWWFkTzYyRk05cU1HZXkvYjh2cFYycks5VlhqQUkKbmpMQllJSkphclhFWk1uMFFLZStzV0hiZzFMRE9pT1Zpd1FRRS8rdDN0aXRKVEtUaUl4ZTB1SDE0MWMrQzBGKwpjNzZiNmhmZ2VraFZZV1hYem4yM1d2NEhFajVpTmNHWjhzVkkwUGY0ai9ZR292Z1ZXUUlEQVFBQm96OHdQVEFPCkJnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0cKQTFVZEV3RUIvd1FDTUFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFbEZsRVhVN3h3RExhT2doeDZVSzlxbgpaRmp2eFg4eXN2U2xvalpOeUhFR0kvODUrVlpDOUkxN3dLRFZGdmJFZnZEcnRQYmpBUXhjS1VsaHlIQ3JpN29yClZwK3dPK2xKbVovVnYxczhkL1ppa0VVSVZYaEpVMjRxcE1WSFB4ZENOckNSWWhmZG1YRUNQRzQwSlN4VWQxbVUKVUF3ZTFYU2wyc2tBeTAyR0NKVElVZTFTaVBrZDFBMngzaDRYa1lZSWlOc2RlblR0Yi9COGxLcUxKL3dCT3J5RgpJY1RHMHhic1NGK2RsL09Pb1JhaC9pZnV4SkZjcURrUjRXcUV1OEF2VXR4ZjFla1NDSHFBVTU0VWVDTWxSbjlWCmZUdGo4bXFEc1ZpcjV1T2g2Sm1pOGhOZm9rQncwRlNRQkQvcmpJdGMrbkJwYVU2aHBGaHZ3YUxzUG5HbzROYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBczVhWVlwUnl2SmxtUUxHeVZZRWJsWHpQdXlkdmJ4MG5YKzRVdStQNTJzYmNBZHVFClR1cERyNGljZWYxVExmL3puenNrTXZEZzdjRHh5bllpOGMyc1N2RW1wTCtsbjdDa2VqQkxiOThWdTJOZlVlT3EKaUxkdjdDM2F4dnVSaXJTZ091aWd5eGtFYm91VmJkWnZSUlgvd1ZOb2llUHRzTm8wN1ZJbWpITWNEQnNmWXVJNgp4LzREVTJrNUFkWm1CQWQvbWlXcVdCQ1lhZE82MkZNOXFNR2V5L2I4dnBWMnJLOVZYakFJbmpMQllJSkphclhFClpNbjBRS2Urc1dIYmcxTERPaU9WaXdRUUUvK3QzdGl0SlRLVGlJeGUwdUgxNDFjK0MwRitjNzZiNmhmZ2VraFYKWVdYWHpuMjNXdjRIRWo1aU5jR1o4c1ZJMFBmNGovWUdvdmdWV1FJREFRQUJBb0lCQUJma2JpdVhVbGh6RkI2QgpSWmVJa0xIbm8vOWpOTGtVcU50allsREkrTUc1ZVNXcUhjVWQ5NWxQMUhtS1VWbXFWckFWZnpCanlaajM5WE1aCkduY1BCT0FIaXp1WjM2QUtNU2VzYXl6Y0Foa25GRlJodEp0eHhDc293cFY4ZkpWMmlHYXQ4azV5NnBzR2FQL3UKNm1qSGozb1o3YXVDcm1tNzdoU3d2RDR0UmtyNXk3bWI2ZjlZaVpOdzkxR1U0OTVUV0ZJZGZDS2J4K2FMcVZmWApjQW80b0NlRGdRMGNva0hIMERlcGhaL0hyblNBNWRhNmlzVWhZa2RKR0Zaek1DZVlnSEF3d01IT0FQMlJCVTllCkhoOGFYbFgyR1krM0Z4d1EvbzgxSWRUQVlYNVhUbUZaV0FHNHZQbTVCeWdXT0MzWnZiL0RmSW5HQkY2b2NuVGcKNmJHWC9BMENnWUVBMlE1Vk1OaXZ2V1lPdlg1TnJJcVV0YkFFOW53aW93d0FNNnhob2Y5Z2tDaWFvNDZaWmhwRApCbEl5V2s5aUloczY2TEluUk1nUEhQNERza29CcDVvK1ZUWTJmZGdXZ1A2UkJlSTFvWHRhNGtNdGRFZnF5RXJWCmt1T1BzL3oxSm5RZThqaVN0TU1RaHM5K1Q0Tk9zMmxTVTJQVU5Jekh0b2tuWmd3VnFOSXkvMDhDZ1lFQTA4OVMKRUZQd3JBdkJkWW1UaTZvbS9SUGJEUEFwYmVKdkpUekdMN1h0R1ZKTitXU3E5VmVOU0F0LzNDRzhqOE15MEtDVwpOTEV3cDd2NncxWlV0RzQrSnFXNjIyNzJ3VVpKOVZlVjBaU2hJR1N2cytnNkVXZUhiekdSbzZiblYxK3hjY2FFCnBINERuUGdnaDFCM05iV2J4RkRneXBIQWIvQUFPTjJ1YjRqbk50Y0NnWUJ1VHVSb2tKYXZjR0JwV1Bqc2lQa08KWk1nQTVCRk9QMWtTNmJZc2QvYUJETUdhQVd4Z0FWU3lyNjg3U2tDYkNLK2xkblNTZGdHSVFHZHNna1BaQTRCTwpHZUVUajIvUVdvOGxLRk1OSC8yT0k0bkVJSkJtL2ZFUVYybStsUDJaYjBZUzMwRmZjQXJFR0VzZTZhSmpkMUVKClpDQ0NIRkdhcUpWSFBUajh0T2FKN1FLQmdRQ3hGR2d3Zkd6KytZa1JBaWNYb2ZhY3FPZis1aDVNM3YwN0xaY24KdGpwMmJBZ0NrL1lWemMreFJ1UHJuMHp0Q0MzSW5DbFgvamVHVkROdThoTTVFZDNtSTdLWDJDcDJKWlNaaUZNWgo5OS9KbkVRRTdnYjJIQTd2bUlxQlBuMjAzNjBUU1B3R0pkQlJnR1I1bkgwOXF3cUNVM2ZNQTVUV1FObCtzVjh2Cm9rNWoyd0tCZ1FERnZMN3lQM2FqeG9mbGZtWkxEU3YwWHpVRS95Zi9VUllyS2RNa3FzbEhBZUllMmUzc1VKRi8KL1A1NlRpMFUwZjVKM0xsM1JqZ3FEc2F0UWJ1SThWRks0WW9uNy9mMEVFVlZ4VWFsWFF2bjVOWjN6OWx5UHJVdgo5U096azV4R3VOOWtIRURQRXRyTG1kcVJ6cDJFZ29pME9Zakdhck80MXRqN1duYnZGU1RCM1E9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```

**Comment by NeonSludge** [comment]
The variables should use actual PEM-formatted data as their values, not paths.
For example, we're currently populating them like this:
```
...
env:
- name: LS_USER_CERTIFICATE                                                                                                                                                                                                         
  valueFrom:                                                                                                                                                                                                                        
    secretKeyRef:                                                                                                                                                                                                                   
      key: certificate                                                                                                                                                                                                              
      name: linstor-mtls-auth                                                                                                                                                                                                       
- name: LS_USER_KEY                                                                                                                                                                                                                 
  valueFrom:                                                                                                                                                                                                                        
    secretKeyRef:                                                                                                                                                                                                                   
      key: key                                                                                                                                                                                                                      
      name: linstor-mtls-auth                                                                                                                                                                                                       
- name: LS_ROOT_CA                                                                                                                                                                                                                  
  valueFrom:                                                                                                                                                                                                                        
    secretKeyRef:                                                                                                                                                                                                                   
      key: ca                                                                                                                                                                                                                      
      name: linstor-mtls-auth
```
