### ISSUE TITLE
ReadWriteMany accessMode

### ISSUE THREAD

**Issue by jbanety** [piraeusdatastore/linstor-csi#69]
Hi,
I'm trying to create a `StatefulSet` with a `ReadWriteMany` accessMode.
It doesn't work. Is it possible to do `ReadWriteMany` access mode with Linstor and Lisntor CSI ?

#### Events on `test-0` :
```
Events:
  Type     Reason                  Age                    From                                  Message
  ----     ------                  ----                   ----                                  -------
  Warning  FailedScheduling        <unknown>              default-scheduler                     persistentvolumeclaim "data" not found
  Normal   Scheduled               <unknown>              default-scheduler                     Successfully assigned default/test-0 to node2
  Normal   SuccessfulAttachVolume  8m18s                  attachdetach-controller               AttachVolume.Attach succeeded for volume "pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196"
  Warning  FailedMount             7m31s (x3 over 8m3s)   kubelet, node2  MountVolume.SetUp failed for volume "pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = NodePublishVolume failed for pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196: mounting volume failed: invalid parameter: resourcegroup does not belong to paramKey values
  Warning  FailedMount             3m58s (x2 over 6m16s)  kubelet, node2  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[default-token-m9cnr data]: timed out waiting for the condition
  Warning  FailedMount             111s (x8 over 8m3s)    kubelet, node2  MountVolume.SetUp failed for volume "pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = NodePublishVolume failed for pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196: mounting volume failed: invalid parameter: drbdoptions/net/allow-two-primaries does not belong to paramKey values
  Warning  FailedMount             104s                   kubelet, node2  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data default-token-m9cnr]: timed out waiting for the condition
```

#### `kubectl logs linstor-csi-node-pvdjb  -n linstor -c linstor-csi-plugin` :
```
time="2020-04-30T06:13:33Z" level=debug msg="method called" func="github.com/sirupsen/logrus.(*Entry).Debug" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:277" linstorCSIComponent=driver method=/csi.v1.Node/NodeGetCapabilities nodeID=node2 provisioner=linstor.csi.linbit.com req= resp="capabilities:<rpc:<type:GET_VOLUME_STATS > > " version=v0.7.4-9-g7383849
time="2020-04-30T06:13:33Z" level=debug msg="looking up resource by CSI volume id" func="github.com/sirupsen/logrus.(*Entry).Debug" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:277" csiVolumeID=pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 linstorCSIComponent=client
time="2020-04-30T06:13:33Z" level=info msg="curl -X 'GET' -H 'Accept: application/json' 'https://linstor-controller:3371/v1/resource-definitions/pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196'"
time="2020-04-30T06:13:33Z" level=debug msg="converted resource definition to volume" func="github.com/sirupsen/logrus.(*Entry).Debug" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:277" linstorCSIComponent=client resourceDefinition="{Name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 ExternalName:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 Props:map[Aux/csi-volume-annotations:{\"name\":\"pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196\",\"id\":\"pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196\",\"createdBy\":\"linstor.csi.linbit.com\",\"creationTime\":\"2020-04-30T06:03:00.12667645Z\",\"sizeBytes\":1073741824,\"readonly\":false,\"parameters\":{\"DrbdOptions/Net/allow-two-primaries\":\"yes\",\"resourceGroup\":\"linstor_group\",\"storagePool\":\"pool_linstor\"},\"snapshots\":[]} DrbdOptions/Net/allow-two-primaries:yes DrbdOptions/Resource/quorum:off DrbdPrimarySetOn:NODE1 StorPoolName:pool_linstor] Flags:[] LayerData:[{Type:DRBD Data:0xc0003d2e10} {Type:STORAGE Data:<nil>}] Uuid:d4b77817-bf44-405a-93c0-c40035fca705}" volume="&{Name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 ID:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 CreatedBy:linstor.csi.linbit.com CreationTime:2020-04-30 06:03:00.12667645 +0000 UTC SizeBytes:1073741824 Readonly:false Parameters:map[DrbdOptions/Net/allow-two-primaries:yes resourceGroup:linstor_group storagePool:pool_linstor] Snapshots:[]}"
time="2020-04-30T06:13:33Z" level=debug msg="getting assignment info" func="github.com/sirupsen/logrus.(*Entry).Debug" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:277" linstorCSIComponent=client targetNode=node2 volume="&{Name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 ID:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 CreatedBy:linstor.csi.linbit.com CreationTime:2020-04-30 06:03:00.12667645 +0000 UTC SizeBytes:1073741824 Readonly:false Parameters:map[DrbdOptions/Net/allow-two-primaries:yes resourceGroup:linstor_group storagePool:pool_linstor] Snapshots:[]}"
time="2020-04-30T06:13:33Z" level=info msg="curl -X 'GET' -H 'Accept: application/json' 'https://linstor-controller:3371/v1/resource-definitions/pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196/resources/node2/volumes/0'"
time="2020-04-30T06:13:33Z" level=debug msg="found assignment info" func="github.com/sirupsen/logrus.(*Entry).Debug" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:277" linstorCSIComponent=client volumeAssignment="&{Vol:0xc000208800 Node:node2 Path:/dev/drbd1000}"
time="2020-04-30T06:13:33Z" level=error msg="method failed" func="github.com/sirupsen/logrus.(*Entry).Error" file="/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:297" error="rpc error: code = Internal desc = NodePublishVolume failed for pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196: mounting volume failed: invalid parameter: drbdoptions/net/allow-two-primaries does not belong to paramKey values" linstorCSIComponent=driver method=/csi.v1.Node/NodePublishVolume nodeID=node2 provisioner=linstor.csi.linbit.com req="volume_id:\"pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196\" target_path:\"/var/lib/kubelet/pods/eecc1e3b-df42-4012-a2d9-24fadf59ef18/volumes/kubernetes.io~csi/pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:\"csi.storage.k8s.io/ephemeral\" value:\"false\" > volume_context:<key:\"csi.storage.k8s.io/pod.name\" value:\"test-0\" > volume_context:<key:\"csi.storage.k8s.io/pod.namespace\" value:\"default\" > volume_context:<key:\"csi.storage.k8s.io/pod.uid\" value:\"eecc1e3b-df42-4012-a2d9-24fadf59ef18\" > volume_context:<key:\"csi.storage.k8s.io/serviceAccount.name\" value:\"default\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1588184499057-8081-linstor.csi.linbit.com\" > " resp="<nil>" version=v0.7.4-9-g7383849
```

#### linstor controller
```
$ linstor storage-pool list
+----------------------------------------------------------------------------------------------------------------------------------+
| StoragePool          | Node  | Driver   | PoolName   | FreeCapacity | TotalCapacity | CanSnapshots | State |
|==================================================================================================================================|
| DfltDisklessStorPool | node1 | DISKLESS |            |              |               | False        | Ok    |
| DfltDisklessStorPool | node2 | DISKLESS |            |              |               | False        | Ok    |
| pool_linstor         | node1 | LVM      | vg_linstor |   334.34 GiB |    335.35 GiB | False        | Ok    |
| pool_linstor         | node2 | LVM      | vg_linstor |   335.35 GiB |    335.35 GiB | False        | Ok    |
+----------------------------------------------------------------------------------------------------------------------------------+

$ 
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Node  | Resource                                 | StoragePool          | VolNr | MinorNr | DeviceName    | Allocated | InUse  |    State |
|=================================================================================================================================================================|
| node1 | pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 | pool_linstor         |     0 |    1000 | /dev/drbd1000 |  1.00 GiB | Unused | UpToDate |
| node2 | pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 | DfltDisklessStorPool |     0 |    1000 | /dev/drbd1000 |           | Unused | Diskless |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------+

$ linstor resource-group list
+------------------------------------------------------------------------+
| ResourceGroup | SelectFilter                    | VlmNrs | Description |
|========================================================================|
| DfltRscGrp    | PlaceCount: 2                   |        |             |
|------------------------------------------------------------------------|
| linstor_group | PlaceCount: 1                   | 0      |             |
|               | StoragePool: pool_linstor       |        |             |
|               | LayerStack: ['DRBD', 'STORAGE'] |        |             |
+------------------------------------------------------------------------+

$ linstor resource-group list-properties linstor_group
+----------------------------------------------------+
| Key                                 | Value        |
|====================================================|
| DrbdOptions/Net/allow-two-primaries | yes          |
| StorPoolName                        | pool_linstor |
+----------------------------------------------------+

```

#### ```drbdadm status``` on node2
```
pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 role:Secondary
  disk:Diskless
  node1 role:Secondary
    peer-disk:UpToDate
```

#### ```drbdsetup events``` on node2
```
exists resource name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 role:Secondary suspended:no
exists connection name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 peer-node-id:0 conn-name:node1 connection:Connected role:Secondary
exists device name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 volume:0 minor:1000 disk:Diskless client:yes quorum:yes
exists peer-device name:pvc-e1d40fd7-0967-40c1-8c05-9c4a460b7196 peer-node-id:0 conn-name:node1 volume:0 replication:Established peer-disk:UpToDate peer-client:no resync-suspended:no
exists -
```

#### Definition
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # The name used to identify this StorageClass.
  name: linstor-basic-storage-class
  # The name used to match this StorageClass with a provisioner.
  # linstor.csi.linbit.com is the name that the LINSTOR CSI plugin uses to identify itself
provisioner: linstor.csi.linbit.com
parameters:
  # LINSTOR will provision volumes from the drbdpool storage pool configured
  # On the satellite nodes in the LINSTOR cluster specified in the plugin's deployment
  storagePool: "pool_linstor"
  resourceGroup: "linstor_group"
  DrbdOptions/Net/allow-two-primaries: "yes"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  serviceName: test
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: debug
          image: alpine:3.11
          command: ["/bin/sh"]
          stdin: true
          tty: true
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
            readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: linstor-basic-storage-class
---
```

**Comment by rck** [comment]
This is being worked on. By default you get a mounted directory with a file system on a DRBD device. The DRBD device/the resource (per default) is not allowed to be dual primary, and even if so, having multiple writers on the file system would break anyways.

The only thing supported right now is raw block mode, with setting DRBD two-primaries via the storage class and having them dual primary while live migration (e.g., kubevirt).

**Comment by jbanety** [comment]
OK. Thanks for the reply.
I gone further with :
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # The name used to identify this StorageClass.
  name: linstor-basic-storage-class
  # The name used to match this StorageClass with a provisioner.
  # linstor.csi.linbit.com is the name that the LINSTOR CSI plugin uses to identify itself
provisioner: linstor.csi.linbit.com
parameters:
  # LINSTOR will provision volumes from the drbdpool storage pool configured
  # On the satellite nodes in the LINSTOR cluster specified in the plugin's deployment
  storagePool: "pool_linstor"
  DrbdOptions/Net/allow-two-primaries: "yes"
  placementCount: "2"
  placementPolicy: "AutoPlace"
```

Here my volumes are OK on the two nodes with the resource created correctly (no Diskless).
But still in error.

Can I help somehow on this ?

**Comment by rck** [comment]
Exactly, but now you mount the FS on two nodes, which really really is not a good idea. Contributions are always welcome, but AFAIK there is a team working on it, so just waiting might be the best for now. @alexzhc , how is the progress on that?

**Comment by jbanety** [comment]
OK. I was able to do ReadWriteMany access with Rook and Ceph but performances are better with Linstor.
My goal is to create load balancing on web app with access to the same filesystem to store and read files.

**Comment by roosemberth** [comment]
Hi!

I have a very similar use-case as @jbanety commented above: I have many applications, which I want to horizontally scale and need to have access to a shared FS.

@rck: You mentioned work was being done on it. Is it open source? If so where can I find more information or the ongoing development?

**Comment by rck** [comment]
I don't know, I'm not working on this part, @alexzhc is still the one that could give updates on it.

**Comment by Jordanhf-dc** [comment]
Hi,
Would also like to combine Linstor's performance and ReadWriteMany access for our usecase. 
An update to have a rough idea of when / if this might happen to set expectations would be welcome @alexzhc , thanks.

**Comment by alexzhc** [comment]
Integrating an NFS export by using a NFS-Ganesha POD on top of a drbd RWO volume is not hard as demonstrated by Rook-NFS. However, by doing so, the NFS-Ganesha POD with the drbd RWO volume needs to failover in a reasonable RTO in case of node failure. However, besides 5-minutes k8s node timeout, currently in CSI, RWO volume attachment failover has a hard-coded timeout of [6 minutes](https://github.com/kubernetes/kubernetes/blob/ee297b6f4d78daaf2f71c78a05203698581ca40a/pkg/controller/volume/attachdetach/attach_detach_controller.go#L95). Such a long failover time will cause NFS mount to go stale. 

We need to solve the RWO failover RTO issue before implementing NFS export.

**Comment by kvaps** [comment]
Hi, take a look at [nfs-server-provisioner](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/) project, we're using it together with linstor for having ReadWriteMany volumes.

**Comment by jbanety** [comment]
Hi @kvaps, it sounds interesting.
Are NFS performances good enough for a heavy loaded web app? 
Do you have a working example with linstor, NFS provisionnel and kube-fencing?

**Comment by kvaps** [comment]
> Are NFS performances good enough for a heavy loaded web app?

Performance is fine, you can see my benchmarks for comparison:
https://gist.github.com/kvaps/8c2831ca15cf161a11e62cc4276793f7

> Do you have a working example with linstor, NFS provisionnel and kube-fencing

For the nfs-server-provisioner, we're using the helm chart:
https://github.com/kvaps/nfs-server-provisioner-chart

here is example values:
```yaml
  persistence:
    enabled: true
    size: 50Gi
    storageClass: linstor-1
  storageClass:
    name: example-nfs
```

After deployment, you can request new volume using `example-nfs` storageclass

Fencing is very specific to your environment, here is an example for HP ilo 
https://raw.githubusercontent.com/kvaps/kube-fencing/master/deploy/examples/hp-ilo.yaml
