### ISSUE TITLE
ClusterRoleBinding for linstor-csi-snapshotter-role missing in example for 1.17

### ISSUE THREAD

**Issue by Retrospector** [piraeusdatastore/linstor-csi#82]
Since I've never tried the snapshot functionality so far I did not realize it.
Until now, after the logs of `csi-snapshotter` grew to a noticable size, filled with messages like this:
```
E0831 06:31:15.580904       1 reflector.go:156] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1beta1.VolumeSnapshotClass: volumesnapshotclasses.snapshot.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:linstor-csi-controller-sa" cannot list resource "volumesnapshotclasses" in API group "snapshot.storage.k8s.io" at the cluster scope
```
After a bit of digging I noticed that in the example for 1.17, there was a ClusterRole for the Snapshotter (`linstor-csi-snapshotter-role`) but no binding that attaches the Role to the `linstor-csi-controller-sa` ServiceAccount.

I guess adding a ClusterRoleBinding like the one found in the examples for older versions should do it:
```yaml
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linstor-csi-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: linstor-csi-controller-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: linstor-csi-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
```

Or is there a particular reason this role binding is removed from the 1.17 example?
